export const DATA = [
  {
    id: 1,
    name: "T-Shirt",
    brand: "Adidas",
    price: 90,
    image: "/images/adult.jpg",
    slug: "t-shirt",
    category: "Shirts",
    rating: 4.1,
    numOfReviews: 9,
    countInStocks: 11,
    description:
      "Fashion eCommerce refers to the buy and sell transactions of fashion and apparel products online, specifically through eCommerce platforms.",
  },
  {
    id: 2,
    name: "Dress",
    brand: "Gucci",
    price: 190,
    image: "/images/blonde.jpg",
    slug: "new-dress",
    category: "Dresses",
    rating: 4.2,
    numOfReviews: 12,
    countInStocks: 23,
    description:
      "Fashion eCommerce refers to the buy and sell transactions of fashion and apparel products online, specifically through eCommerce platforms.",
  },
  {
    id: 3,
    name: "Children Jackets",
    brand: "Fashion Hub",
    price: 50,
    image: "/images/children.jpg",
    slug: "children-jacket",
    category: "Jackets",
    rating: 4.5,
    numOfReviews: 15,
    countInStocks: 25,
    description:
      "Fashion eCommerce refers to the buy and sell transactions of fashion and apparel products online, specifically through eCommerce platforms.",
  },
  {
    id: 4,
    name: "Black Dress",
    brand: "Sana Safinaz",
    price: 130,
    image: "/images/fashion.jpg",
    slug: "black-dress",
    category: "Dresses",
    rating: 3.9,
    numOfReviews: 222,
    countInStocks: 125,
    description:
      "Fashion eCommerce refers to the buy and sell transactions of fashion and apparel products online, specifically through eCommerce platforms.",
  },
  {
    id: 5,
    name: "White T-Shirt",
    brand: "Adidas",
    price: 170,
    image: "/images/girl.jpg",
    slug: "white-shirt",
    category: "Shirts",
    rating: 4.5,
    numOfReviews: 12,
    countInStocks: 15,
    description:
      "Fashion eCommerce refers to the buy and sell transactions of fashion and apparel products online, specifically through eCommerce platforms.",
  },
  {
    id: 6,
    name: "Orange Jacket",
    brand: "Armaani",
    price: 200,
    image: "/images/orange.jpg",
    slug: "orange-jacket",
    category: "Jackets",
    rating: 4.9,
    numOfReviews: 32,
    countInStocks: 45,
    description:
      "Fashion eCommerce refers to the buy and sell transactions of fashion and apparel products online, specifically through eCommerce platforms.",
  },
  {
    id: 7,
    name: "Ladies Scarf",
    brand: "Sana Safinaz",
    price: 100,
    image: "/images/woman.jpg",
    slug: "ladies-scarf",
    category: "Scarfs",
    rating: 4.7,
    numOfReviews: 11,
    countInStocks: 11,
    description:
      "Fashion eCommerce refers to the buy and sell transactions of fashion and apparel products online, specifically through eCommerce platforms.",
  },
  {
    id: 8,
    name: "White Dress",
    brand: "Sana Safinaz",
    price: 100,
    image: "/images/white.jpg",
    slug: "white-dress",
    category: "Dresses",
    rating: 4.5,
    numOfReviews: 12,
    countInStocks: 15,
    description:
      "Fashion eCommerce refers to the buy and sell transactions of fashion and apparel products online, specifically through eCommerce platforms.",
  },
];
